# Generated by Django 4.0.2 on 2022-08-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_alter_word_correctaudio_alter_word_correctphonetics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='spokenAudio',
            field=models.FileField(upload_to='documents'),
        ),
    ]
