# Generated by Django 4.0.2 on 2022-08-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_word_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='spokenAudio',
            field=models.FileField(blank=True, upload_to='documents'),
        ),
    ]
