# Generated by Django 4.0.2 on 2022-08-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_alter_word_spokenaudio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='correctAudio',
        ),
    ]
