# Generated by Django 4.0.2 on 2022-08-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_remove_word_correctaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='spokenAudio',
            field=models.FileField(blank=True, upload_to='API/views/documents'),
        ),
    ]
