# Generated by Django 4.0.4 on 2022-08-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0011_alter_word_spokenaudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.TextField(),
        ),
    ]
